stages:
  - static-analysis
  - dynamic-analysis

snyk_scan:
  stage: static-analysis
  script:
    - snyk test
  only:
    - main

sonarqube_scan:
  stage: static-analysis
  script:
    - sonar-scanner
  only:
    - main

semgrep_scan:
  stage: static-analysis
  script:
    - semgrep --config auto .
  only:
    - main

trufflehog_scan:
  stage: static-analysis
  script:
    - trufflehog git file://. --only-verified
  only:
    - main

nmap_scan:
  stage: dynamic-analysis
  script:
    - nmap -sV localhost
  only:
    - main

sqlmap_scan:
  stage: dynamic-analysis
  script:
    - sqlmap -u "http://localhost:3000" --batch
  only:
    - main

zap_scan:
  stage: dynamic-analysis
  script:
    - zap-baseline.py -t http://localhost:3000 -r zap_report.html
  only:
    - main
