services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces/devsec-pipeline/app:/project   # σωστό mount
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - devsec

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devsec

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    depends_on:
      - sonarqube
    volumes:
      - ./app:/usr/src
    command: >
      sonar-scanner
      -Dsonar.projectKey=devsec-pipeline
      -Dsonar.sources=/usr/src
      -Dsonar.host.url=http://sonarqube:9000
      -Dsonar.login=admin
      -Dsonar.password=admin
    networks:
      - devsec

  zaproxy:
    image: ghcr.io/zaproxy/zaproxy:weekly
    container_name: zaproxy
    ports:
      - "8081:8080"
    volumes:
      - ./reports:/zap/wrk
    networks:
      - devsec

networks:
  devsec:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
