services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  zaproxy:
    image: ghcr.io/zaproxy/zaproxy:weekly   # ✅ σωστό image από GitHub Container Registry
    container_name: zaproxy
    ports:
      - "8081:8080"
    volumes:
      - ./reports:/zap/wrk

volumes:
  sonarqube_data:
  sonarqube_extensions:
