name: CI - Static Security

on:
  push:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: windows-latest
    steps:
      # --- Checkout repo ---
      - uses: actions/checkout@v4

      # --- Python setup ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install semgrep
        run: pip install semgrep

      # --- Semgrep scan (UTF-8 fix) ---
      - name: Run semgrep
        env:
          PYTHONUTF8: 1
        run: semgrep --config auto --output semgrep-results.sarif

      # --- Node.js setup ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Install dependencies
        working-directory: vulnerable-app
        run: npm install

      - name: Debug workspace (optional)
        run: Get-ChildItem -Recurse | Select-Object FullName

      - name: Snyk auth
        working-directory: vulnerable-app
        shell: pwsh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $env:SNYK_TOKEN

      - name: Snyk test
        working-directory: vulnerable-app
        shell: pwsh
        run: snyk test --json || true

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Generate Snyk HTML report
        run: snyk test --json | snyk-to-html -o snyk-report.html

      # --- TruffleHog scan ---
      - name: TruffleHog scan
        run: docker run --rm -v "${{ github.workspace }}:/src" trufflesecurity/trufflehog:latest filesystem --path /src || true

      # --- Trigger Jenkins dynamic scan ---
      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_TRIGGER_TOKEN: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        run:  curl -X POST " https://6ae9ea8527b4.ngrok-free.app/job/devsec-pipeline/build?JENKINS_TRIGGER_TOKEN=MYTOKEN123" --user "velti:1100f3e8fa586d715a4ec41b1bf1db6afe"



  dynamic-analysis:
    runs-on: windows-latest
    needs: static-analysis
    steps:
      - uses: actions/checkout@v4

       # --- Install Chocolatey packages ---
      - name: Install Nmap
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install nmap -y

      # --- Nmap scan ---
      - name: Nmap Scan
        shell: pwsh
        run: 
          try { nmap -sV localhost } catch { Write-Host "Nmap scan failed" }

      # --- SQLMap scan ---
      - name: SQLMap Scan
        shell: pwsh
        run: 
          try { pip install sqlmap; sqlmap -u "http://localhost/vulnerable-endpoint" --batch } catch { Write-Host "SQLMap scan failed" }

      # ------
      