name: CI - Static Security

on:
  push:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: windows-latest
    steps:
      # --- Checkout repo ---
      - uses: actions/checkout@v4

      # --- Python setup ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install semgrep
        run: pip install semgrep

      # --- Semgrep scan (UTF-8 fix) ---
      - name: Run semgrep
        env:
          PYTHONUTF8: 1
        run: semgrep --config auto --output semgrep-results.sarif

      # --- Node.js setup ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Install dependencies
        working-directory: vulnerable-app
        run: npm install

      - name: Debug workspace (optional)
        run: Get-ChildItem -Recurse | Select-Object FullName

      - name: Snyk auth
        working-directory: vulnerable-app
        shell: pwsh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $env:SNYK_TOKEN

      - name: Snyk test with HTML output
        working-directory: vulnerable-app
        shell: pwsh
        run: snyk test --json | snyk-to-html -o snyk-report.html

      # --- TruffleHog scan ---
      - name: TruffleHog scan
        run: docker run --rm -v "${{ github.workspace }}:/src" trufflesecurity/trufflehog:latest filesystem --path /src || true

      # --- Trigger Jenkins dynamic scan ---
      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_TRIGGER_TOKEN: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        run: |
          curl -X POST "$JENKINS_URL/job/devsecops-dynamic/build?token=$JENKINS_TRIGGER_TOKEN" --user $JENKINS_USER:$JENKINS_API_TOKEN
